# Generated by Django 4.0.4 on 2022-05-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDS', models.CharField(default='', max_length=500)),
                ('name', models.CharField(default='', max_length=500)),
                ('date', models.CharField(default='', max_length=500)),
                ('gpa', models.CharField(default='', max_length=500)),
                ('gender', models.CharField(default='', max_length=500)),
                ('level', models.CharField(default='', max_length=500)),
                ('departement', models.CharField(default='', max_length=500)),
                ('Email', models.CharField(default='', max_length=500)),
                ('mobile', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
