# Generated by Django 4.0.4 on 2022-05-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0002_alter_informations_ids_alter_informations_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
    ]
