# Generated by Django 3.2.13 on 2022-05-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0003_alter_informations_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='date',
            field=models.CharField(default='', max_length=500),
        ),
    ]
