# Generated by Django 3.2.13 on 2022-05-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0004_alter_informations_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='IDS',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='level',
        ),
    ]
