# Generated by Django 3.2.13 on 2022-05-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0006_auto_20220517_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='IDS',
        ),
        migrations.AlterField(
            model_name='informations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
