# Generated by Django 3.2.13 on 2022-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0007_auto_20220517_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='gender',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='informations',
            name='level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
