# Generated by Django 3.2.13 on 2022-05-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0009_alter_informations_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informations',
            old_name='Email',
            new_name='email',
        ),
    ]
