# Generated by Django 3.2.13 on 2022-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0013_alter_informations_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='id',
        ),
        migrations.AddField(
            model_name='informations',
            name='id_no',
            field=models.AutoField(default=None, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='informations',
            name='studID',
            field=models.IntegerField(null=True),
        ),
    ]
