# Generated by Django 3.2.13 on 2022-05-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0014_auto_20220517_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informations',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='informations',
            name='studID',
        ),
        migrations.AddField(
            model_name='informations',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
