# Generated by Django 3.2.13 on 2022-05-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0015_auto_20220517_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='studID',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
