# Generated by Django 3.2.13 on 2022-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0016_informations_studid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='studID',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
