# Generated by Django 3.2.13 on 2022-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0017_alter_informations_studid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informations',
            name='studID',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=99999999),
        ),
    ]
